CMakeLists.txt: integrate googletest as submodule
9rum/libindex pull request #5
Opened 2024-01-19 07:23 UTC by hnbrds

2024-01-19 08:09 UTC, 9rum commented
@hnbrds Thanks for filing this PR. Have you verified it in your local?

2024-01-22 07:32 UTC, hnbrds commented
@9rum 
For verification, I've wrote a sample test code `test.cc`
`#include "gtest/gtest.h

TEST(Foo, Sum) {
  EXPECT_EQ(2, 1+1)
}`

Compiled as an executable file,
image below shows the execution result and it seems to work fine.

<img width="1280" alt="스크린샷 2024-01-22 오후 4 04 35" src="https://github.com/9rum/mako/assets/13926810/b1511b2d-6783-4cdb-8c5a-6090b2ed833c">

also works with ctest

<img width="1280" alt="스크린샷 2024-01-22 오후 4 32 38" src="https://github.com/9rum/mako/assets/13926810/9eb8737c-21c6-4ed9-8ee6-b551385634b1">

2024-01-23 07:36 UTC, hnbrds commented
1. Instead of adding all tests respectively with `add_test()`,
`gtest_discover_tests()` automatically discovers tests included in the executable.

```
root@622569c8ba94:/workspace/build# ctest .
Test project /workspace/build
    Start 1: Foo.Sum
1/1 Test #1: Foo.Sum ..........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

2. Added option to make a decision whether to build test files; note that the option is set to `OFF`.

2024-01-23 08:12 UTC, hnbrds commented
rather than using additional option `MAKO_BUILD_TESTING`, used automatically generated option `BUILD_TESTING` by CTest.

(https://cmake.org/cmake/help/latest/module/CTest.html)
As `BUILD_TESTING` option is enabled by default,
explicitly state option `-DBUILD_TESTING=OFF` in order to disable test file build.

2024-01-23 08:21 UTC, 9rum requested changes

2024-01-23 08:21 UTC, 9rum commented on CMakeLists.txt
> +include CTest
Please change this line to ``include(CTest)``.

2024-01-24 02:13 UTC, 9rum approved these changes

2024-01-24 02:14 UTC, merged